version: '3.8'

services:
  wedl-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wedl-api
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - TZ=UTC
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - downloads:/downloads
    networks:
      - wedl-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  downloads:
    driver: local

networks:
  wedl-network:
    driver: bridge
